/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package JTLMM.resource.JTLMM.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class JTLMMFollowSetProvider {
	
	public final static JTLMM.resource.JTLMM.IJTLMMExpectedElement TERMINALS[] = new JTLMM.resource.JTLMM.IJTLMMExpectedElement[53];
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] FEATURES = new org.eclipse.emf.ecore.EStructuralFeature[13];
	
	public final static JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] LINKS = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[275];
	
	public final static JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] EMPTY_LINK_ARRAY = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[0];
	
	public static void initializeTerminals0() {
		TERMINALS[0] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_0);
		TERMINALS[1] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_1);
		TERMINALS[2] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_3);
		TERMINALS[3] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_1_0_0_0);
		TERMINALS[4] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_5);
		TERMINALS[5] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_4_0_0_1_0_0_0);
		TERMINALS[6] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_7);
		TERMINALS[7] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedBooleanTerminal(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_2_0_0_0);
		TERMINALS[8] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_2_0_0_1);
		TERMINALS[9] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_0_0_0_10);
		TERMINALS[10] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_1_0_0_1);
		TERMINALS[11] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_1_0_0_2);
		TERMINALS[12] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_2_0_0_2);
		TERMINALS[13] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_2_0_0_4);
		TERMINALS[14] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_12_0_0_0);
		TERMINALS[15] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedBooleanTerminal(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_3_0_0_0);
		TERMINALS[16] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedBooleanTerminal(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_3_0_0_1);
		TERMINALS[17] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_3_0_0_2);
		TERMINALS[18] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_0_0);
		TERMINALS[19] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_1_0);
		TERMINALS[20] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_0);
		TERMINALS[21] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_2_0_0_10);
		TERMINALS[22] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_3_0_0_3);
		TERMINALS[23] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_0_2);
		TERMINALS[24] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_7_0_0_0);
		TERMINALS[25] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_8_0_0_0);
		TERMINALS[26] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedBooleanTerminal(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_9_0_0_0);
		TERMINALS[27] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_10_0_0_0);
		TERMINALS[28] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_11_0_0_0);
		TERMINALS[29] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_0_5);
		TERMINALS[30] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_0_3_0_0_2);
		TERMINALS[31] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_1_2);
		TERMINALS[32] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_1_5);
		TERMINALS[33] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_1_3_0_0_2);
		TERMINALS[34] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_2_2);
		TERMINALS[35] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_2_4);
		TERMINALS[36] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_4_0_2_3_0_0_2_0_0_0);
		TERMINALS[37] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_2);
		TERMINALS[38] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_3_0_0_1);
		TERMINALS[39] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_4_0_0_0);
		TERMINALS[40] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_5_0_0_1);
		TERMINALS[41] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_5_0_0_2_0_0_2_0_0_0);
		TERMINALS[42] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_5_0_0_4);
		TERMINALS[43] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_8_0_0_2_0_0_1_0_0_0);
		TERMINALS[44] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_8_0_0_3);
		TERMINALS[45] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_6_0_0_4_0_0_1);
		TERMINALS[46] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_7_0_0_2);
		TERMINALS[47] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_8_0_0_1);
		TERMINALS[48] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_11_0_0_1);
		TERMINALS[49] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_11_0_0_2);
		TERMINALS[50] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_12_0_0_1_0_0_1);
		TERMINALS[51] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedCsString(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_12_0_0_2);
		TERMINALS[52] = new JTLMM.resource.JTLMM.mopp.JTLMMExpectedStructuralFeature(JTLMM.resource.JTLMM.grammar.JTLMMGrammarInformationProvider.JTLMM_12_0_0_1_0_0_3);
	}
	
	public static void initializeTerminals() {
		initializeTerminals0();
	}
	
	public static void initializeFeatures0() {
		FEATURES[0] = JTLMM.JTL.JTLPackage.eINSTANCE.getTransformation().getEStructuralFeature(JTLMM.JTL.JTLPackage.TRANSFORMATION__MODEL_PARAMETER);
		FEATURES[1] = JTLMM.JTL.JTLPackage.eINSTANCE.getTransformation().getEStructuralFeature(JTLMM.JTL.JTLPackage.TRANSFORMATION__RELATION);
		FEATURES[2] = JTLMM.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTLMM.JTL.JTLPackage.RELATION__VARIABLE);
		FEATURES[3] = JTLMM.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTLMM.JTL.JTLPackage.RELATION__DOMAIN);
		FEATURES[4] = JTLMM.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTLMM.JTL.JTLPackage.RELATION__WHEN);
		FEATURES[5] = JTLMM.JTL.JTLPackage.eINSTANCE.getPattern().getEStructuralFeature(JTLMM.JTL.JTLPackage.PATTERN__TEMPLATE_EXPRESSION);
		FEATURES[6] = JTLMM.JTL.JTLPackage.eINSTANCE.getDomain().getEStructuralFeature(JTLMM.JTL.JTLPackage.DOMAIN__PATTERN);
		FEATURES[7] = JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate().getEStructuralFeature(JTLMM.JTL.JTLPackage.PREDICATE__CONDITION_EXPRESSION);
		FEATURES[8] = JTLMM.JTL.JTLPackage.eINSTANCE.getPattern().getEStructuralFeature(JTLMM.JTL.JTLPackage.PATTERN__PREDICATE);
		FEATURES[9] = JTLMM.JTL.JTLPackage.eINSTANCE.getRelation().getEStructuralFeature(JTLMM.JTL.JTLPackage.RELATION__WHERE);
		FEATURES[10] = JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp().getEStructuralFeature(JTLMM.imperativeocl.ImperativeoclPackage.ASSIGN_EXP__VALUE);
		FEATURES[11] = JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp().getEStructuralFeature(JTLMM.template.TemplatePackage.OBJECT_TEMPLATE_EXP__INSIDE);
		FEATURES[12] = JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp().getEStructuralFeature(JTLMM.essentialocl.EssentialoclPackage.OPERATION_CALL_EXP__ARGUMENT);
	}
	
	public static void initializeFeatures() {
		initializeFeatures0();
	}
	
	public static void initializeLinks0() {
		LINKS[0] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]);
		LINKS[1] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]);
		LINKS[2] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[3] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[4] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[5] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[6] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[7] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[8] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[9] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[10] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[11] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[12] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[13] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[14] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[15] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[16] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[17] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[18] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[19] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[20] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[21] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[22] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[23] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[24] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[25] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[26] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[27] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[28] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[29] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[30] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[31] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[32] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[33] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[34] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[35] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[36] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[37] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[38] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[39] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[40] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[41] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[42] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[43] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[44] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[45] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[46] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[47] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[48] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[49] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[50] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[51] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[52] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[53] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[54] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[55] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]);
		LINKS[56] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]);
		LINKS[57] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]);
		LINKS[58] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[59] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]);
		LINKS[60] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[61] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[62] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[63] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[64] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[65] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[66] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[67] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[68] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[69] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[70] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[71] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[72] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[73] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[74] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[75] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[76] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[77] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[78] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[79] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[80] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[81] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[82] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[83] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[84] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[85] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[86] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[87] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[88] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[89] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[90] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[91] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[92] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[93] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[94] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[95] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[96] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[97] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[98] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[99] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[100] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[101] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[102] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[103] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[104] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[105] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[106] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[107] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[108] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[109] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[110] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[111] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[112] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[113] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[114] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[115] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[116] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[117] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[118] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[119] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[120] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[121] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[122] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[123] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[124] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[125] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[126] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[127] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[128] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[129] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[130] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[131] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[132] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[133] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[134] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[135] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[136] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[137] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[138] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[139] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[140] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[141] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[142] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[143] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[144] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[145] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[146] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[147] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[148] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[149] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[150] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[151] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[152] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[153] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[154] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[155] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[156] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[157] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[158] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[159] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]);
		LINKS[160] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[161] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]);
		LINKS[162] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[163] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]);
		LINKS[164] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[165] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]);
		LINKS[166] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[167] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]);
		LINKS[168] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[169] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]);
		LINKS[170] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]);
		LINKS[171] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[172] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[173] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[174] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]);
		LINKS[175] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[176] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[177] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[178] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[179] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[180] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[181] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[182] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[183] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[184] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[185] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[186] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[187] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[188] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[189] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[190] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[191] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[192] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[193] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[194] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[195] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[196] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[197] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[198] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[199] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[200] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[201] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[202] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[203] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[204] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[205] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]);
		LINKS[206] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]);
		LINKS[207] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[208] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[209] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[210] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[211] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[212] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[213] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[214] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[215] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[216] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[217] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[218] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[219] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[220] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[221] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[222] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[223] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[224] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[225] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[226] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[227] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[228] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[229] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[230] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[231] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]);
		LINKS[232] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]);
		LINKS[233] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]);
		LINKS[234] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]);
		LINKS[235] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]);
		LINKS[236] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]);
		LINKS[237] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]);
		LINKS[238] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]);
		LINKS[239] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]);
		LINKS[240] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]);
		LINKS[241] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]);
		LINKS[242] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]);
		LINKS[243] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[244] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[245] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[246] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[247] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[248] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[249] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[250] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[251] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[252] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[253] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[254] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[255] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[256] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[257] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[258] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[259] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[260] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[261] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]);
		LINKS[262] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]);
		LINKS[263] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]);
		LINKS[264] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]);
		LINKS[265] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]);
		LINKS[266] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]);
		LINKS[267] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]);
		LINKS[268] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[269] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[270] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]);
		LINKS[271] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[272] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
		LINKS[273] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]);
		LINKS[274] = new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]);
	}
	
	public static void initializeLinks() {
		initializeLinks0();
	}
	
	public static void wire0() {
		TERMINALS[0].addFollower(TERMINALS[1], EMPTY_LINK_ARRAY);
		TERMINALS[1].addFollower(TERMINALS[2], EMPTY_LINK_ARRAY);
		TERMINALS[2].addFollower(TERMINALS[3], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]), });
		TERMINALS[2].addFollower(TERMINALS[4], EMPTY_LINK_ARRAY);
		TERMINALS[5].addFollower(TERMINALS[3], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getModel(), FEATURES[0]), });
		TERMINALS[4].addFollower(TERMINALS[6], EMPTY_LINK_ARRAY);
		TERMINALS[6].addFollower(TERMINALS[7], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[6].addFollower(TERMINALS[8], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[3].addFollower(TERMINALS[10], EMPTY_LINK_ARRAY);
		TERMINALS[10].addFollower(TERMINALS[11], EMPTY_LINK_ARRAY);
		TERMINALS[11].addFollower(TERMINALS[5], EMPTY_LINK_ARRAY);
		TERMINALS[11].addFollower(TERMINALS[4], EMPTY_LINK_ARRAY);
		TERMINALS[7].addFollower(TERMINALS[8], EMPTY_LINK_ARRAY);
		TERMINALS[8].addFollower(TERMINALS[12], EMPTY_LINK_ARRAY);
		TERMINALS[12].addFollower(TERMINALS[13], EMPTY_LINK_ARRAY);
		TERMINALS[13].addFollower(TERMINALS[14], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]), });
		TERMINALS[13].addFollower(TERMINALS[15], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[16], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[17], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[13].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[13].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[13].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[13].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[21].addFollower(TERMINALS[7], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[21].addFollower(TERMINALS[8], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getRelation(), FEATURES[1]), });
		TERMINALS[21].addFollower(TERMINALS[9], EMPTY_LINK_ARRAY);
		TERMINALS[15].addFollower(TERMINALS[16], EMPTY_LINK_ARRAY);
		TERMINALS[15].addFollower(TERMINALS[17], EMPTY_LINK_ARRAY);
		TERMINALS[16].addFollower(TERMINALS[17], EMPTY_LINK_ARRAY);
		TERMINALS[17].addFollower(TERMINALS[22], EMPTY_LINK_ARRAY);
		TERMINALS[22].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]), });
		TERMINALS[22].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]), });
		TERMINALS[22].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[6]), });
		TERMINALS[18].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[23].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[23].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[30].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[30].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[29].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[29].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[29].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[29].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[19].addFollower(TERMINALS[31], EMPTY_LINK_ARRAY);
		TERMINALS[31].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[31].addFollower(TERMINALS[32], EMPTY_LINK_ARRAY);
		TERMINALS[33].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[33].addFollower(TERMINALS[32], EMPTY_LINK_ARRAY);
		TERMINALS[32].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[32].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[32].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[32].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[34].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[34].addFollower(TERMINALS[35], EMPTY_LINK_ARRAY);
		TERMINALS[36].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[36].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[36].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[36].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[36].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[36].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[7]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPredicate(), FEATURES[8]), });
		TERMINALS[35].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[35].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[35].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[9]), });
		TERMINALS[35].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[20].addFollower(TERMINALS[37], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[38], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[37].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[38].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[39].addFollower(TERMINALS[45], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[45].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[40].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]), });
		TERMINALS[40].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[41].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[11]), });
		TERMINALS[42].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[42].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[24].addFollower(TERMINALS[46], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[46].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[25].addFollower(TERMINALS[47], EMPTY_LINK_ARRAY);
		TERMINALS[47].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]), });
		TERMINALS[47].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[43].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[12]), });
		TERMINALS[43].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[12]), });
		TERMINALS[44].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[44].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[26].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[27].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[28].addFollower(TERMINALS[48], EMPTY_LINK_ARRAY);
		TERMINALS[48].addFollower(TERMINALS[49], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[30], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[24], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.imperativeocl.ImperativeoclPackage.eINSTANCE.getAssignExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[25], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getOperationCallExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[26], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getBooleanLiteralExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[27], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariableExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[28], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getStringLiteralExp(), FEATURES[10]), });
		TERMINALS[49].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[14].addFollower(TERMINALS[50], EMPTY_LINK_ARRAY);
		TERMINALS[14].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[52], EMPTY_LINK_ARRAY);
		TERMINALS[52].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[14], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.essentialocl.EssentialoclPackage.eINSTANCE.getVariable(), FEATURES[2]), });
		TERMINALS[51].addFollower(TERMINALS[15], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[16], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[17], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getDomain(), FEATURES[3]), });
		TERMINALS[51].addFollower(TERMINALS[18], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[51].addFollower(TERMINALS[19], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[51].addFollower(TERMINALS[20], new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature[] {new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.template.TemplatePackage.eINSTANCE.getObjectTemplateExp(), FEATURES[5]), new JTLMM.resource.JTLMM.mopp.JTLMMContainedFeature(JTLMM.JTL.JTLPackage.eINSTANCE.getPattern(), FEATURES[4]), });
		TERMINALS[51].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
	}
	
	public static void wire() {
		wire0();
	}
	
	static {
		// initialize the arrays
		initializeTerminals();
		initializeFeatures();
		initializeLinks();
		// wire the terminals
		wire();
	}
}
