<?xml version="1.0" encoding="ISO-8859-1"?>
<ASP:Transformation xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ASP="http://asp.ecore" name="uml2rdbms">
  <elements xsi:type="ASP:Literal" name="uml"/>
  <elements xsi:type="ASP:Literal" name="Class"/>
  <elements xsi:type="ASP:Metanode" name="uml!Class" literals="//@elements.0 //@elements.1"/>
  <elements xsi:type="ASP:Literal" name="rdbms"/>
  <elements xsi:type="ASP:Literal" name="Table"/>
  <elements xsi:type="ASP:Metanode" name="rdbms!Table" literals="//@elements.3 //@elements.4"/>
  <elements xsi:type="ASP:Literal" name="node0:uml!Class"/>
  <elements xsi:type="ASP:Node" name="node0:uml!Class" literals="//@elements.0 //@elements.6 //@elements.1"/>
  <elements xsi:type="ASP:Literal" name="node1:rdbms!Table"/>
  <elements xsi:type="ASP:Node" name="node1:rdbms!Table" literals="//@elements.3 //@elements.8 //@elements.4"/>
  <relations id="AttributeToColumn" name="AttributeToColumn" type="bidirectional">
    <patterns xsi:type="ASP:LeftPattern" element="//@elements.2" name="Class" type="node"/>
    <patterns xsi:type="ASP:RightPattern" element="//@elements.5" name="Table" type="node"/>
  </relations>
  <constraints name="Constraint1_0">
    <expressions xsi:type="ASP:Terminal" name="c" element="//@elements.7"/>
    <expressions xsi:type="ASP:Not" name="t" element="//@elements.9"/>
  </constraints>
  <constraints name="Constraint1_1">
    <expressions xsi:type="ASP:Terminal" name="t" element="//@elements.9"/>
    <expressions xsi:type="ASP:Not" name="c" element="//@elements.7"/>
  </constraints>
</ASP:Transformation>
