/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package ASP.resource.ASP.ui;

/**
 * A CodeCompletionHelper can be used to derive completion proposals for partial
 * documents. It runs the parser generated by EMFText in a special mode (i.e., the
 * rememberExpectedElements mode). Based on the elements that are expected by the
 * parser for different regions in the document, valid proposals are computed.
 */
public class ASPCodeCompletionHelper {
	
	private ASP.resource.ASP.mopp.ASPAttributeValueProvider attributeValueProvider = new ASP.resource.ASP.mopp.ASPAttributeValueProvider();
	
	private ASP.resource.ASP.IASPMetaInformation metaInformation = new ASP.resource.ASP.mopp.ASPMetaInformation();
	
	/**
	 * Computes a set of proposals for the given document assuming the cursor is at
	 * 'cursorOffset'. The proposals are derived using the meta information, i.e., the
	 * generated language plug-in.
	 * 
	 * @param originalResource
	 * @param content the documents content
	 * @param cursorOffset
	 * 
	 * @return
	 */
	public ASP.resource.ASP.ui.ASPCompletionProposal[] computeCompletionProposals(ASP.resource.ASP.IASPTextResource originalResource, String content, int cursorOffset) {
		org.eclipse.emf.ecore.resource.ResourceSet resourceSet = new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();
		// the shadow resource needs the same URI because reference resolvers may use the
		// URI to resolve external references
		ASP.resource.ASP.IASPTextResource resource = (ASP.resource.ASP.IASPTextResource) resourceSet.createResource(originalResource.getURI());
		java.io.ByteArrayInputStream inputStream = new java.io.ByteArrayInputStream(content.getBytes());
		ASP.resource.ASP.IASPMetaInformation metaInformation = resource.getMetaInformation();
		ASP.resource.ASP.IASPTextParser parser = metaInformation.createParser(inputStream, null);
		ASP.resource.ASP.mopp.ASPExpectedTerminal[] expectedElements = parseToExpectedElements(parser, resource, cursorOffset);
		if (expectedElements == null) {
			return new ASP.resource.ASP.ui.ASPCompletionProposal[0];
		}
		if (expectedElements.length == 0) {
			return new ASP.resource.ASP.ui.ASPCompletionProposal[0];
		}
		java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedAfterCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset));
		java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedBeforeCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset - 1));
		setPrefixes(expectedAfterCursor, content, cursorOffset);
		setPrefixes(expectedBeforeCursor, content, cursorOffset);
		// First, we derive all possible proposals from the set of elements that are
		// expected at the cursor position.
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> allProposals = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>();
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> rightProposals = deriveProposals(expectedAfterCursor, content, resource, cursorOffset);
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> leftProposals = deriveProposals(expectedBeforeCursor, content, resource, cursorOffset - 1);
		removeKeywordsEndingBeforeIndex(leftProposals, cursorOffset);
		// Second, the set of left proposals (i.e., the ones before the cursor) is checked
		// for emptiness. If the set is empty, the right proposals (i.e., the ones after
		// the cursor) are also considered. If the set is not empty, the right proposal
		// are discarded, because it does not make sense to propose them until the element
		// before the cursor was completed.
		allProposals.addAll(leftProposals);
		// Count the proposals before the cursor that match the prefix
		int leftMatchingProposals = 0;
		for (ASP.resource.ASP.ui.ASPCompletionProposal leftProposal : leftProposals) {
			if (leftProposal.getMatchesPrefix()) {
				leftMatchingProposals++;
			}
		}
		if (leftMatchingProposals == 0) {
			allProposals.addAll(rightProposals);
		}
		// Third, the proposals are sorted according to their relevance. Proposals that
		// matched the prefix are preferred over ones that did not. Finally, proposals are
		// sorted alphabetically.
		final java.util.List<ASP.resource.ASP.ui.ASPCompletionProposal> sortedProposals = new java.util.ArrayList<ASP.resource.ASP.ui.ASPCompletionProposal>(allProposals);
		java.util.Collections.sort(sortedProposals);
		org.eclipse.emf.ecore.EObject root = null;
		if (!resource.getContents().isEmpty()) {
			root = resource.getContents().get(0);
		}
		for (ASP.resource.ASP.ui.ASPCompletionProposal proposal : sortedProposals) {
			proposal.setRoot(root);
		}
		return sortedProposals.toArray(new ASP.resource.ASP.ui.ASPCompletionProposal[sortedProposals.size()]);
	}
	
	public ASP.resource.ASP.mopp.ASPExpectedTerminal[] parseToExpectedElements(ASP.resource.ASP.IASPTextParser parser, ASP.resource.ASP.IASPTextResource resource, int cursorOffset) {
		final java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements = parser.parseToExpectedElements(null, resource, cursorOffset);
		if (expectedElements == null) {
			return new ASP.resource.ASP.mopp.ASPExpectedTerminal[0];
		}
		removeDuplicateEntries(expectedElements);
		removeInvalidEntriesAtEnd(expectedElements);
		return expectedElements.toArray(new ASP.resource.ASP.mopp.ASPExpectedTerminal[expectedElements.size()]);
	}
	
	/**
	 * Removes all expected elements that refer to the same terminal and that start at
	 * the same position.
	 */
	protected void removeDuplicateEntries(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements) {
		int size = expectedElements.size();
		// We split the list of expected elements into buckets where each bucket contains
		// the elements that start at the same position.
		java.util.Map<Integer, java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal>> map = new java.util.LinkedHashMap<Integer, java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal>>();
		for (int i = 0; i < size; i++) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtIndex = expectedElements.get(i);
			int start1 = elementAtIndex.getStartExcludingHiddenTokens();
			java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> list = map.get(start1);
			if (list == null) {
				list = new java.util.ArrayList<ASP.resource.ASP.mopp.ASPExpectedTerminal>();
				map.put(start1, list);
			}
			list.add(elementAtIndex);
		}
		
		// Then, we remove all duplicate elements from each bucket individually.
		for (int position : map.keySet()) {
			java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> list = map.get(position);
			removeDuplicateEntriesFromBucket(list);
		}
		
		// After removing all duplicates, we merge the buckets.
		expectedElements.clear();
		for (int position : map.keySet()) {
			java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> list = map.get(position);
			expectedElements.addAll(list);
		}
	}
	
	/**
	 * Removes all expected elements that refer to the same terminal. Attention: This
	 * method assumes that the given list of expected terminals contains only elements
	 * that start at the same position.
	 */
	protected void removeDuplicateEntriesFromBucket(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements) {
		int size = expectedElements.size();
		for (int i = 0; i < size - 1; i++) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtIndex = expectedElements.get(i);
			ASP.resource.ASP.IASPExpectedElement terminal = elementAtIndex.getTerminal();
			for (int j = i + 1; j < size;) {
				ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtNext = expectedElements.get(j);
				if (terminal.equals(elementAtNext.getTerminal())) {
					expectedElements.remove(j);
					size--;
				} else {
					j++;
				}
			}
		}
	}
	
	protected void removeInvalidEntriesAtEnd(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1;) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtIndex = expectedElements.get(i);
			ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtNext = expectedElements.get(i + 1);
			
			// If the two expected elements have a different parent in the syntax definition,
			// we must not discard the second element, because is probably stems from a parent
			// rule.
			ASP.resource.ASP.grammar.ASPSyntaxElement symtaxElementOfThis = elementAtIndex.getTerminal().getSymtaxElement();
			ASP.resource.ASP.grammar.ASPSyntaxElement symtaxElementOfNext = elementAtNext.getTerminal().getSymtaxElement();
			boolean differentParent = symtaxElementOfNext.getParent() != symtaxElementOfThis.getParent();
			
			boolean sameStartExcludingHiddenTokens = elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens();
			boolean differentFollowSet = elementAtIndex.getFollowSetID() != elementAtNext.getFollowSetID();
			if (sameStartExcludingHiddenTokens && differentFollowSet && !differentParent) {
				expectedElements.remove(i + 1);
			} else {
				i++;
			}
		}
	}
	
	/**
	 * Removes all proposals for keywords that end before the given index.
	 */
	protected void removeKeywordsEndingBeforeIndex(java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> proposals, int index) {
		java.util.List<ASP.resource.ASP.ui.ASPCompletionProposal> toRemove = new java.util.ArrayList<ASP.resource.ASP.ui.ASPCompletionProposal>();
		for (ASP.resource.ASP.ui.ASPCompletionProposal proposal : proposals) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal = proposal.getExpectedTerminal();
			ASP.resource.ASP.IASPExpectedElement terminal = expectedTerminal.getTerminal();
			if (terminal instanceof ASP.resource.ASP.mopp.ASPExpectedCsString) {
				ASP.resource.ASP.mopp.ASPExpectedCsString csString = (ASP.resource.ASP.mopp.ASPExpectedCsString) terminal;
				int startExcludingHiddenTokens = expectedTerminal.getStartExcludingHiddenTokens();
				if (startExcludingHiddenTokens + csString.getValue().length() - 1 < index) {
					toRemove.add(proposal);
				}
			}
		}
		proposals.removeAll(toRemove);
	}
	
	protected String findPrefix(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements, ASP.resource.ASP.mopp.ASPExpectedTerminal expectedAtCursor, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return "";
		}
		int end = 0;
		for (ASP.resource.ASP.mopp.ASPExpectedTerminal expectedElement : expectedElements) {
			if (expectedElement == expectedAtCursor) {
				final int start = expectedElement.getStartExcludingHiddenTokens();
				if (start >= 0  && start < Integer.MAX_VALUE) {
					end = start;
				}
				break;
			}
		}
		end = Math.min(end, cursorOffset);
		final String prefix = content.substring(end, Math.min(content.length(), cursorOffset));
		return prefix;
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> deriveProposals(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements, String content, ASP.resource.ASP.IASPTextResource resource, int cursorOffset) {
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> resultSet = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>();
		for (ASP.resource.ASP.mopp.ASPExpectedTerminal expectedElement : expectedElements) {
			resultSet.addAll(deriveProposals(expectedElement, content, resource, cursorOffset));
		}
		return resultSet;
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> deriveProposals(final ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, String content, ASP.resource.ASP.IASPTextResource resource, int cursorOffset) {
		ASP.resource.ASP.IASPExpectedElement expectedElement = (ASP.resource.ASP.IASPExpectedElement) expectedTerminal.getTerminal();
		if (expectedElement instanceof ASP.resource.ASP.mopp.ASPExpectedCsString) {
			ASP.resource.ASP.mopp.ASPExpectedCsString csString = (ASP.resource.ASP.mopp.ASPExpectedCsString) expectedElement;
			return handleKeyword(expectedTerminal, csString, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof ASP.resource.ASP.mopp.ASPExpectedBooleanTerminal) {
			ASP.resource.ASP.mopp.ASPExpectedBooleanTerminal expectedBooleanTerminal = (ASP.resource.ASP.mopp.ASPExpectedBooleanTerminal) expectedElement;
			return handleBooleanTerminal(expectedTerminal, expectedBooleanTerminal, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof ASP.resource.ASP.mopp.ASPExpectedEnumerationTerminal) {
			ASP.resource.ASP.mopp.ASPExpectedEnumerationTerminal expectedEnumerationTerminal = (ASP.resource.ASP.mopp.ASPExpectedEnumerationTerminal) expectedElement;
			return handleEnumerationTerminal(expectedTerminal, expectedEnumerationTerminal, expectedTerminal.getPrefix());
		} else if (expectedElement instanceof ASP.resource.ASP.mopp.ASPExpectedStructuralFeature) {
			final ASP.resource.ASP.mopp.ASPExpectedStructuralFeature expectedFeature = (ASP.resource.ASP.mopp.ASPExpectedStructuralFeature) expectedElement;
			final org.eclipse.emf.ecore.EStructuralFeature feature = expectedFeature.getFeature();
			final org.eclipse.emf.ecore.EClassifier featureType = feature.getEType();
			final org.eclipse.emf.ecore.EObject container = findCorrectContainer(expectedTerminal);
			
			// Here it gets really crazy. We need to modify the model in a way that reflects
			// the state the model would be in, if the expected terminal were present. After
			// computing the corresponding completion proposals, the original state of the
			// model is restored. This procedure is required, because different models can be
			// required for different completion situations. This can be particularly observed
			// when the user has not yet typed a character that starts an element to be
			// completed.
			final java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> proposals = new java.util.ArrayList<ASP.resource.ASP.ui.ASPCompletionProposal>();
			expectedTerminal.materialize(new Runnable() {
				
				public void run() {
					if (feature instanceof org.eclipse.emf.ecore.EReference) {
						org.eclipse.emf.ecore.EReference reference = (org.eclipse.emf.ecore.EReference) feature;
						if (featureType instanceof org.eclipse.emf.ecore.EClass) {
							if (reference.isContainment()) {
								// the FOLLOW set should contain only non-containment references
								assert false;
							} else {
								proposals.addAll(handleNCReference(expectedTerminal, container, reference, expectedTerminal.getPrefix(), expectedFeature.getTokenName()));
							}
						}
					} else if (feature instanceof org.eclipse.emf.ecore.EAttribute) {
						org.eclipse.emf.ecore.EAttribute attribute = (org.eclipse.emf.ecore.EAttribute) feature;
						if (featureType instanceof org.eclipse.emf.ecore.EEnum) {
							org.eclipse.emf.ecore.EEnum enumType = (org.eclipse.emf.ecore.EEnum) featureType;
							proposals.addAll(handleEnumAttribute(expectedTerminal, expectedFeature, enumType, expectedTerminal.getPrefix(), container));
						} else {
							// handle EAttributes (derive default value depending on the type of the
							// attribute, figure out token resolver, and call deResolve())
							proposals.addAll(handleAttribute(expectedTerminal, expectedFeature, container, attribute, expectedTerminal.getPrefix()));
						}
					} else {
						// there should be no other subclass of EStructuralFeature
						assert false;
					}
				}
			});
			// Return the proposals that were computed in the closure call.
			return proposals;
		} else {
			// there should be no other class implementing IExpectedElement
			assert false;
		}
		return java.util.Collections.emptyList();
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleEnumAttribute(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, ASP.resource.ASP.mopp.ASPExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EEnum enumType, String prefix, org.eclipse.emf.ecore.EObject container) {
		java.util.Collection<org.eclipse.emf.ecore.EEnumLiteral> enumLiterals = enumType.getELiterals();
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> result = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>();
		for (org.eclipse.emf.ecore.EEnumLiteral literal : enumLiterals) {
			String unResolvedLiteral = literal.getLiteral();
			// use token resolver to get de-resolved value of the literal
			ASP.resource.ASP.IASPTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
			ASP.resource.ASP.IASPTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(expectedFeature.getTokenName());
			String resolvedLiteral = tokenResolver.deResolve(unResolvedLiteral, expectedFeature.getFeature(), container);
			boolean matchesPrefix = matches(resolvedLiteral, prefix);
			result.add(new ASP.resource.ASP.ui.ASPCompletionProposal(expectedTerminal, resolvedLiteral, prefix, matchesPrefix, expectedFeature.getFeature(), container));
		}
		return result;
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleNCReference(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EReference reference, String prefix, String tokenName) {
		// proposals for non-containment references are derived by calling the reference
		// resolver switch in fuzzy mode.
		ASP.resource.ASP.IASPReferenceResolverSwitch resolverSwitch = metaInformation.getReferenceResolverSwitch();
		ASP.resource.ASP.IASPTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
		ASP.resource.ASP.IASPReferenceResolveResult<org.eclipse.emf.ecore.EObject> result = new ASP.resource.ASP.mopp.ASPReferenceResolveResult<org.eclipse.emf.ecore.EObject>(true);
		resolverSwitch.resolveFuzzy(prefix, container, reference, 0, result);
		java.util.Collection<ASP.resource.ASP.IASPReferenceMapping<org.eclipse.emf.ecore.EObject>> mappings = result.getMappings();
		if (mappings != null) {
			java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> resultSet = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>();
			for (ASP.resource.ASP.IASPReferenceMapping<org.eclipse.emf.ecore.EObject> mapping : mappings) {
				org.eclipse.swt.graphics.Image image = null;
				if (mapping instanceof ASP.resource.ASP.mopp.ASPElementMapping<?>) {
					ASP.resource.ASP.mopp.ASPElementMapping<?> elementMapping = (ASP.resource.ASP.mopp.ASPElementMapping<?>) mapping;
					Object target = elementMapping.getTargetElement();
					// de-resolve reference to obtain correct identifier
					ASP.resource.ASP.IASPTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
					final String identifier = tokenResolver.deResolve(elementMapping.getIdentifier(), reference, container);
					if (target instanceof org.eclipse.emf.ecore.EObject) {
						image = getImage((org.eclipse.emf.ecore.EObject) target);
					}
					boolean matchesPrefix = matches(identifier, prefix);
					resultSet.add(new ASP.resource.ASP.ui.ASPCompletionProposal(expectedTerminal, identifier, prefix, matchesPrefix, reference, container, image));
				}
			}
			return resultSet;
		}
		return java.util.Collections.emptyList();
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleAttribute(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, ASP.resource.ASP.mopp.ASPExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EAttribute attribute, String prefix) {
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> resultSet = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>();
		Object[] defaultValues = attributeValueProvider.getDefaultValues(attribute);
		if (defaultValues != null) {
			for (Object defaultValue : defaultValues) {
				if (defaultValue != null) {
					ASP.resource.ASP.IASPTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
					String tokenName = expectedFeature.getTokenName();
					if (tokenName != null) {
						ASP.resource.ASP.IASPTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
						if (tokenResolver != null) {
							String defaultValueAsString = tokenResolver.deResolve(defaultValue, attribute, container);
							boolean matchesPrefix = matches(defaultValueAsString, prefix);
							resultSet.add(new ASP.resource.ASP.ui.ASPCompletionProposal(expectedTerminal, defaultValueAsString, prefix, matchesPrefix, expectedFeature.getFeature(), container));
						}
					}
				}
			}
		}
		return resultSet;
	}
	
	/**
	 * Creates a set of completion proposals from the given keyword.
	 */
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleKeyword(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, ASP.resource.ASP.mopp.ASPExpectedCsString csString, String prefix) {
		String proposal = csString.getValue();
		boolean matchesPrefix = matches(proposal, prefix);
		return java.util.Collections.singleton(new ASP.resource.ASP.ui.ASPCompletionProposal(expectedTerminal, proposal, prefix, matchesPrefix, null, null));
	}
	
	/**
	 * Creates a set of (two) completion proposals from the given boolean terminal.
	 */
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleBooleanTerminal(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, ASP.resource.ASP.mopp.ASPExpectedBooleanTerminal expectedBooleanTerminal, String prefix) {
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> result = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>(2);
		ASP.resource.ASP.grammar.ASPBooleanTerminal booleanTerminal = expectedBooleanTerminal.getBooleanTerminal();
		result.addAll(handleLiteral(expectedTerminal, booleanTerminal.getAttribute(), prefix, booleanTerminal.getTrueLiteral()));
		result.addAll(handleLiteral(expectedTerminal, booleanTerminal.getAttribute(), prefix, booleanTerminal.getFalseLiteral()));
		return result;
	}
	
	/**
	 * Creates a set of completion proposals from the given enumeration terminal. For
	 * each enumeration literal one proposal is created.
	 */
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleEnumerationTerminal(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, ASP.resource.ASP.mopp.ASPExpectedEnumerationTerminal expectedEnumerationTerminal, String prefix) {
		java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> result = new java.util.LinkedHashSet<ASP.resource.ASP.ui.ASPCompletionProposal>(2);
		ASP.resource.ASP.grammar.ASPEnumerationTerminal enumerationTerminal = expectedEnumerationTerminal.getEnumerationTerminal();
		java.util.Map<String, String> literalMapping = enumerationTerminal.getLiteralMapping();
		for (String literalName : literalMapping.keySet()) {
			result.addAll(handleLiteral(expectedTerminal, enumerationTerminal.getAttribute(), prefix, literalMapping.get(literalName)));
		}
		return result;
	}
	
	protected java.util.Collection<ASP.resource.ASP.ui.ASPCompletionProposal> handleLiteral(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal, org.eclipse.emf.ecore.EAttribute attribute, String prefix, String literal) {
		if ("".equals(literal)) {
			return java.util.Collections.emptySet();
		}
		boolean matchesPrefix = matches(literal, prefix);
		return java.util.Collections.singleton(new ASP.resource.ASP.ui.ASPCompletionProposal(expectedTerminal, literal, prefix, matchesPrefix, null, null));
	}
	
	/**
	 * Calculates the prefix for each given expected element. The prefix depends on
	 * the current document content, the cursor position, and the position where the
	 * element is expected.
	 */
	protected void setPrefixes(java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedElements, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return;
		}
		for (ASP.resource.ASP.mopp.ASPExpectedTerminal expectedElement : expectedElements) {
			String prefix = findPrefix(expectedElements, expectedElement, content, cursorOffset);
			expectedElement.setPrefix(prefix);
		}
	}
	
	public ASP.resource.ASP.mopp.ASPExpectedTerminal[] getElementsExpectedAt(ASP.resource.ASP.mopp.ASPExpectedTerminal[] allExpectedElements, int cursorOffset) {
		java.util.List<ASP.resource.ASP.mopp.ASPExpectedTerminal> expectedAtCursor = new java.util.ArrayList<ASP.resource.ASP.mopp.ASPExpectedTerminal>();
		for (int i = 0; i < allExpectedElements.length; i++) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal expectedElement = allExpectedElements[i];
			int startIncludingHidden = expectedElement.getStartIncludingHiddenTokens();
			int end = getEnd(allExpectedElements, i);
			if (cursorOffset >= startIncludingHidden && cursorOffset <= end) {
				expectedAtCursor.add(expectedElement);
			}
		}
		return expectedAtCursor.toArray(new ASP.resource.ASP.mopp.ASPExpectedTerminal[expectedAtCursor.size()]);
	}
	
	/**
	 * Calculates the end index of the expected element at allExpectedElements[index].
	 * To determine the end, the subsequent expected elements from the array of all
	 * expected elements are used. An element is considered to end one character
	 * before the next elements starts.
	 */
	protected int getEnd(ASP.resource.ASP.mopp.ASPExpectedTerminal[] allExpectedElements, int indexInList) {
		ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtIndex = allExpectedElements[indexInList];
		int startIncludingHidden = elementAtIndex.getStartIncludingHiddenTokens();
		int startExcludingHidden = elementAtIndex.getStartExcludingHiddenTokens();
		for (int i = indexInList + 1; i < allExpectedElements.length; i++) {
			ASP.resource.ASP.mopp.ASPExpectedTerminal elementAtI = allExpectedElements[i];
			int startIncludingHiddenForI = elementAtI.getStartIncludingHiddenTokens();
			int startExcludingHiddenForI = elementAtI.getStartExcludingHiddenTokens();
			if (startIncludingHidden != startIncludingHiddenForI || startExcludingHidden != startExcludingHiddenForI) {
				return startIncludingHiddenForI - 1;
			}
		}
		return Integer.MAX_VALUE;
	}
	
	/**
	 * Checks whether the given proposed string matches the prefix. The two strings
	 * are compared ignoring the case. The prefix is also considered to match if is a
	 * camel case representation of the proposal.
	 */
	protected boolean matches(String proposal, String prefix) {
		if (proposal == null || prefix == null) {
			return false;
		}
		return (proposal.toLowerCase().startsWith(prefix.toLowerCase()) || ASP.resource.ASP.util.ASPStringUtil.matchCamelCase(prefix, proposal) != null) && !proposal.equals(prefix);
	}
	
	protected org.eclipse.swt.graphics.Image getImage(org.eclipse.emf.ecore.EObject element) {
		if (!org.eclipse.core.runtime.Platform.isRunning()) {
			return null;
		}
		org.eclipse.emf.edit.provider.ComposedAdapterFactory adapterFactory = new org.eclipse.emf.edit.provider.ComposedAdapterFactory(org.eclipse.emf.edit.provider.ComposedAdapterFactory.Descriptor.Registry.INSTANCE);
		adapterFactory.addAdapterFactory(new org.eclipse.emf.edit.provider.resource.ResourceItemProviderAdapterFactory());
		adapterFactory.addAdapterFactory(new org.eclipse.emf.ecore.provider.EcoreItemProviderAdapterFactory());
		adapterFactory.addAdapterFactory(new org.eclipse.emf.edit.provider.ReflectiveItemProviderAdapterFactory());
		org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider labelProvider = new org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider(adapterFactory);
		return labelProvider.getImage(element);
	}
	
	protected org.eclipse.emf.ecore.EObject findCorrectContainer(ASP.resource.ASP.mopp.ASPExpectedTerminal expectedTerminal) {
		org.eclipse.emf.ecore.EObject container = expectedTerminal.getContainer();
		org.eclipse.emf.ecore.EClass ruleMetaclass = expectedTerminal.getTerminal().getRuleMetaclass();
		if (ruleMetaclass.isInstance(container)) {
			// container is correct for expected terminal
			return container;
		}
		// the container is wrong
		org.eclipse.emf.ecore.EObject parent = null;
		org.eclipse.emf.ecore.EObject previousParent = null;
		org.eclipse.emf.ecore.EObject correctContainer = null;
		org.eclipse.emf.ecore.EObject hookableParent = null;
		ASP.resource.ASP.grammar.ASPContainmentTrace containmentTrace = expectedTerminal.getContainmentTrace();
		org.eclipse.emf.ecore.EClass startClass = containmentTrace.getStartClass();
		ASP.resource.ASP.mopp.ASPContainedFeature currentLink = null;
		ASP.resource.ASP.mopp.ASPContainedFeature previousLink = null;
		ASP.resource.ASP.mopp.ASPContainedFeature[] containedFeatures = containmentTrace.getPath();
		for (int i = 0; i < containedFeatures.length; i++) {
			currentLink = containedFeatures[i];
			if (i > 0) {
				previousLink = containedFeatures[i - 1];
			}
			org.eclipse.emf.ecore.EClass containerClass = currentLink.getContainerClass();
			hookableParent = findHookParent(container, startClass, currentLink, parent);
			if (hookableParent != null) {
				// we found the correct parent
				break;
			} else {
				previousParent = parent;
				parent = containerClass.getEPackage().getEFactoryInstance().create(containerClass);
				if (parent != null) {
					if (previousParent == null) {
						// replace container for expectedTerminal with correctContainer
						correctContainer = parent;
					} else {
						// This assignment is only performed to get rid of a warning about a potential
						// null pointer access. Variable 'previousLink' cannot be null here, because it is
						// initialized for all loop iterations where 'i' is greather than 0 and for the
						// case where 'i' equals zero, this path is never executed, because
						// 'previousParent' is null in this case.
						ASP.resource.ASP.mopp.ASPContainedFeature link = previousLink;
						ASP.resource.ASP.util.ASPEObjectUtil.setFeature(parent, link.getFeature(), previousParent, false);
					}
				}
			}
		}
		
		if (correctContainer == null) {
			correctContainer = container;
		}
		
		if (currentLink == null) {
			return correctContainer;
		}
		
		hookableParent = findHookParent(container, startClass, currentLink, parent);
		
		final org.eclipse.emf.ecore.EObject finalHookableParent = hookableParent;
		final org.eclipse.emf.ecore.EStructuralFeature finalFeature = currentLink.getFeature();
		final org.eclipse.emf.ecore.EObject finalParent = parent;
		if (parent != null && hookableParent != null) {
			expectedTerminal.setAttachmentCode(new Runnable() {
				
				public void run() {
					ASP.resource.ASP.util.ASPEObjectUtil.setFeature(finalHookableParent, finalFeature, finalParent, false);
				}
			});
		}
		return correctContainer;
	}
	
	/**
	 * Walks up the containment hierarchy to find an EObject that is able to hold
	 * (contain) the given object.
	 */
	protected org.eclipse.emf.ecore.EObject findHookParent(org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EClass startClass, ASP.resource.ASP.mopp.ASPContainedFeature currentLink, org.eclipse.emf.ecore.EObject object) {
		org.eclipse.emf.ecore.EClass containerClass = currentLink.getContainerClass();
		while (container != null) {
			if (containerClass.isInstance(object)) {
				if (startClass.equals(container.eClass())) {
					return container;
				}
			}
			container = container.eContainer();
		}
		return null;
	}
	
}
